import { DayPlan } from './types';

export const THIRTY_DAY_PLAN: DayPlan[] = [
  { day: 1, topic: "Personal Introductions", description: "Mastering the art of introducing yourself and others in formal and informal settings." },
  { day: 2, topic: "Daily Routines", description: "Discussing habits, schedules, and time management." },
  { day: 3, topic: "Socializing & Making Plans", description: "Arranging meetings, invitations, and leisure activities." },
  { day: 4, topic: "Food & Dining", description: "Ordering at restaurants, discussing recipes, and dietary preferences." },
  { day: 5, topic: "Travel & Transport", description: "Navigating airports, train stations, and asking for travel advice." },
  { day: 6, topic: "Weather & Climate", description: "Talking about forecasts, seasons, and climate conditions." },
  { day: 7, topic: "Past Experiences", description: "Sharing stories about holidays, childhood, and past events." },
  { day: 8, topic: "Directions & City Life", description: "Navigating a city, asking for directions, and describing places." },
  { day: 9, topic: "Shopping & Fashion", description: "Buying clothes, negotiating prices, and describing style." },
  { day: 10, topic: "Work & Jobs", description: "Job interviews, workplace communication, and career goals." },
  { day: 11, topic: "Future Goals", description: "Talking about ambitions, predictions, and future plans." },
  { day: 12, topic: "Hobbies & Free Time", description: "Discussing interests, sports, and entertainment." },
  { day: 13, topic: "Health & Wellness", description: "Describing symptoms, visiting a doctor, and healthy lifestyles." },
  { day: 14, topic: "Communication", description: "Phone calls, emails, and messaging etiquette." },
  { day: 15, topic: "Describing People", description: "Personality traits, physical appearance, and character." },
  { day: 16, topic: "Problems & Solutions", description: "Making complaints, solving issues, and customer service." },
  { day: 17, topic: "News & Media", description: "Discussing current events, headlines, and media consumption." },
  { day: 18, topic: "Housing & Home", description: "Describing homes, renting apartments, and furniture." },
  { day: 19, topic: "Entertainment & Arts", description: "Movies, books, music, and cultural events." },
  { day: 20, topic: "Opinions & Debates", description: "Agreeing, disagreeing, and expressing strong opinions." },
  { day: 21, topic: "Culture & Customs", description: "Comparing cultures, traditions, and social etiquette." },
  { day: 22, topic: "Air Travel", description: "Check-in procedures, security, and in-flight conversation." },
  { day: 23, topic: "Formal Writing", description: "Structure of formal letters, applications, and official requests." },
  { day: 24, topic: "Describing Images", description: "Detailed observation and description of visual scenes." },
  { day: 25, topic: "Storytelling", description: "Narrative structures, sequencing events, and creative writing." },
  { day: 26, topic: "Processes & Instructions", description: "Giving and following step-by-step guides." },
  { day: 27, topic: "Education & Learning", description: "School systems, studying habits, and learning new skills." },
  { day: 28, topic: "Parties & Celebrations", description: "Small talk, hosting events, and festive vocabulary." },
  { day: 29, topic: "Technology & Innovation", description: "Gadgets, internet safety, and future tech trends." },
  { day: 30, topic: "Comprehensive Review", description: "Putting it all together: a full assessment of B1 skills." },
];
